export const STATUS_MAP = {
  AVAILABLE: 'AVAILABLE',
  UNAVAILABLE: 'UNAVAILABLE',
  REMOVED: 'REMOVED'
} as const;

export const STATUS = [STATUS_MAP.AVAILABLE, STATUS_MAP.UNAVAILABLE, STATUS_MAP.REMOVED] as const;
